version: '3'
services:
  registry:
    image: registry:2
    volumes:
      - ./registry:/var/lib/registry
    networks:
      - registry
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
  nginx:
    image: nginx:alpine
    networks:
      - registry
    ports:
      - 443:443
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
networks:
  registry:
